"""
Exercise metadata: single source of truth for all exercises.
Each entry defines the exercise name, fitness goal, type, default sets/reps/rest,
and a plain-English description used for TF-IDF similarity ranking.
"""

EXERCISES = [
    # ── Weight Loss ───────────────────────────────────────────────────────────
    {
        "name": "Jumping Jacks",
        "goal": "weight_loss",
        "type": "time",
        "value": 30,
        "sets": 3,
        "rest": 20,
        "description": "A full body cardio exercise to burn calories fast.",
    },
    {
        "name": "Squats",
        "goal": "weight_loss",
        "type": "reps",
        "value": 12,
        "sets": 3,
        "rest": 30,
        "description": "Compound lower-body movement that burns calories and tones legs.",
    },
    {
        "name": "Plank",
        "goal": "weight_loss",
        "type": "time",
        "value": 30,
        "sets": 3,
        "rest": 30,
        "description": "Core hold that engages the whole body and burns calories.",
    },
    # ── Muscle Gain ───────────────────────────────────────────────────────────
    {
        "name": "Push-ups",
        "goal": "muscle_gain",
        "type": "reps",
        "value": 10,
        "sets": 3,
        "rest": 30,
        "description": "Strengthens chest, shoulders, and triceps.",
    },
    {
        "name": "Dumbbell Curls",
        "goal": "muscle_gain",
        "type": "reps",
        "value": 12,
        "sets": 3,
        "rest": 30,
        "description": "Isolates the biceps and builds upper-arm size.",
    },
    {
        "name": "Lunges",
        "goal": "muscle_gain",
        "type": "reps",
        "value": 10,
        "sets": 3,
        "rest": 30,
        "description": "Builds unilateral leg strength and tones glutes.",
    },
    # ── Flexibility ───────────────────────────────────────────────────────────
    {
        "name": "Neck Stretch",
        "goal": "flexibility",
        "type": "time",
        "value": 30,
        "sets": 2,
        "rest": 15,
        "description": "Loosens neck muscles and improves posture.",
    },
    {
        "name": "Hamstring Stretch",
        "goal": "flexibility",
        "type": "time",
        "value": 30,
        "sets": 2,
        "rest": 15,
        "description": "Stretches the hamstrings and improves lower-body flexibility.",
    },
    {
        "name": "Child Pose",
        "goal": "flexibility",
        "type": "time",
        "value": 60,
        "sets": 1,
        "rest": 0,
        "description": "Relaxing yoga stretch for the back and hips.",
    },
    # ── Endurance ─────────────────────────────────────────────────────────────
    {
        "name": "High Knees",
        "goal": "endurance",
        "type": "time",
        "value": 30,
        "sets": 3,
        "rest": 20,
        "description": "Cardio drill that raises heart rate and builds stamina.",
    },
    {
        "name": "Mountain Climbers",
        "goal": "endurance",
        "type": "time",
        "value": 30,
        "sets": 3,
        "rest": 20,
        "description": "Fast-paced core and cardio exercise for endurance.",
    },
    {
        "name": "Burpees",
        "goal": "endurance",
        "type": "reps",
        "value": 10,
        "sets": 3,
        "rest": 30,
        "description": "Full-body movement to boost cardio conditioning.",
    },
    # ── Core Strength ─────────────────────────────────────────────────────────
    {
        "name": "Side Plank",
        "goal": "core_strength",
        "type": "time",
        "value": 30,
        "sets": 3,
        "rest": 20,
        "description": "Builds core stability and strengthens obliques.",
    },
    {
        "name": "Dead Bug",
        "goal": "core_strength",
        "type": "reps",
        "value": 10,
        "sets": 3,
        "rest": 20,
        "description": "Core stability exercise for abs and lower back.",
    },
    {
        "name": "Glute Bridge",
        "goal": "core_strength",
        "type": "reps",
        "value": 12,
        "sets": 3,
        "rest": 20,
        "description": "Strengthens glutes and supports core stability.",
    },
    # ── Balance ───────────────────────────────────────────────────────────────
    {
        "name": "Single-Leg Stand",
        "goal": "balance",
        "type": "time",
        "value": 30,
        "sets": 2,
        "rest": 20,
        "description": "Improves balance and ankle stability.",
    },
    {
        "name": "Heel-to-Toe Walk",
        "goal": "balance",
        "type": "time",
        "value": 30,
        "sets": 2,
        "rest": 20,
        "description": "Enhances coordination and balance control.",
    },
    {
        "name": "Standing March",
        "goal": "balance",
        "type": "time",
        "value": 30,
        "sets": 2,
        "rest": 20,
        "description": "Dynamic balance drill to improve stability.",
    },
]
